/*
act3-1.c
create semaphores and initialize sempahore1=1, sempahore2=0
create  shm segment, with 3 values:
- random  number generated by client
- number of iterations
- comparison result ,0,1,2 according to function compare
*/

#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <sys/shm.h>
#include <semaphore.h>
#include <unistd.h>
#include <sys/types.h>
#include <string.h>

#define SHM_KEY 0x1234

#define NAME1 "/semaphore1"
#define NAME2 "/semaphore2"

void err_sys(const char* text)
{
    perror(text);
    exit(1);
}

struct shmseg {
	int client;
	int iteration;
	int comparison;
};

int main(int argc, char *argv[])
{
    sem_t*  psem1;  //semaphore that control act1-3
    sem_t*  psem2; //semaphore that control act1-4
    int     sem_value;
    int     result;
    int shmid;
    struct shmseg *shmp;
    int i, j;

    shmid = shmget(SHM_KEY, sizeof(struct shmseg), 0666|IPC_CREAT);
    if (shmid == -1) err_sys("Shared Memory Error");

    //attach to the shmp pointer
    shmp = shmat(shmid, NULL, 0);
    if (shmp == (void*)(-1)) err_sys("Shared Memory attachment error");

    shmp->client=0;
    shmp->iteration=0;
    shmp->comparison = 0;

    printf("The random number is %d\n", shmp->client);
    printf("The number of iterations is %d\n", shmp->iteration);
    printf("The comparison value is %d\n", shmp->comparison);

    /* Create psem1 */
    psem1 = (sem_t*)sem_open(NAME1, O_CREAT, 0600, 0);
    if (psem1 == SEM_FAILED) {
        err_sys("Open psem1");
    }

    /* Read and print psem1 */
    result = sem_getvalue(psem1, &sem_value);
    if (result < 0) {
        err_sys("Read psem1");
    }
//    printf("SEM1: %d\n", sem_value);

    /* Wait for sem_value to be 0 */
    while (sem_value > 0) {
        sem_wait(psem1);
        sem_value--;
    }
    if (sem_post(psem1) < 0) {
        err_sys("Post psem1");
    }

    /* Read and print psem1 */
    result = sem_getvalue(psem1, &sem_value);
    if (result < 0) {
        err_sys("Read psem1");
    }
    printf("SEM1: %d\n", sem_value);

    /* Create psem2 */
    psem2 = (sem_t*)sem_open(NAME2, O_CREAT, 0600, 0);
    if (psem2 == SEM_FAILED) {
        err_sys("Open psem2");
    }

    /* Read and print psem2 */
    result = sem_getvalue(psem2, &sem_value);
    if (result < 0) {
        err_sys("Read psem2");
    }
//    printf("SEM2: %d\n", sem_value);

    /* Wait for sem_value to be 0 */
    while (sem_value > 0) {
        sem_wait(psem2);
        sem_value--;
    }

    /* Read and print psem2 */
    result = sem_getvalue(psem2, &sem_value);
    if (result < 0) {
        err_sys("Read psem2");
    }
    printf("SEM2: %d\n", sem_value);

    /* Close psem1 */
    result = sem_close(psem1);
    if (result != 0) {
        err_sys("Close psem1");
    }

    /* Close psem2 */
    result = sem_close(psem2);
    if (result != 0) {
        err_sys("Close psem2");
    }

    //dettach the shmp pointer
    result = shmdt(shmp);
    if (result == (-1)) err_sys("Shared Memory dettachment error");

}
